name: dev_env

channels:
  - conda-forge
  - bioconda

dependencies:
  # Python
  - python=3.12

  # Jupyter
  - jupyterlab
  - ipykernel

  # Bioinformatics
  - mafft

  # Python packages
  - numpy
  - pandas
  - scipy
  - matplotlib
  - biopython

  # Add more tools here
  # - samtools
  # - minimap2
  # - bowtie2

  # Pip dependencies, if you need them
  # - pip
  # - pip:
  #     - some-package
